"""Root results ledger — build ``RESULTS.md`` from every ``experiments/*/RESULTS.csv``.

``RESULTS.md`` is GENERATED output: a notebook calls :func:`build_results_md`; the
file itself is a build artifact and is never hand-edited. The per-experiment
``RESULTS.csv`` files are HETEROGENEOUS (02-lora-sft carries ``pre_evaluation_score``
+ ``acc_OOD`` but NO ``bucket_mean`` column; 05-bottleneck-audit HAS ``bucket_mean``),
so we coalesce a common view and never fabricate a missing ``bucket_mean``.

Pure pandas + stdlib — runs fully offline.
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# common coalesced view (in display order)
_VIEW = ["experiment", "arm", "bucket_mean", "acc_ID", "acc_OOD", "verdict", "note"]


def _first(row: pd.Series, *names: str):
    """First present, non-null value among ``names`` (heterogeneous schemas)."""
    for n in names:
        if n in row and pd.notna(row[n]):
            return row[n]
    return None


def _coalesce_rows(csv: Path) -> list[dict]:
    experiment = csv.parent.name
    df = pd.read_csv(csv)
    has_bucket_mean = "bucket_mean" in df.columns
    rows: list[dict] = []
    for _, r in df.iterrows():
        bucket_mean = r["bucket_mean"] if has_bucket_mean else np.nan
        note_bits = []
        if not has_bucket_mean:
            note_bits.append("no bucket_mean col in RESULTS.csv")
        rows.append(
            {
                "experiment": experiment,
                "arm": _first(r, "arm", "run", "run_name") or "",
                "bucket_mean": float(bucket_mean) if pd.notna(bucket_mean) else np.nan,
                "acc_ID": _first(r, "acc_ID"),
                "acc_OOD": _first(r, "acc_OOD"),
                "verdict": _first(r, "verdict") or "",
                "note": "; ".join(note_bits),
            }
        )
    return rows


def _fmt(v) -> str:
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return ""
    if isinstance(v, float):
        return f"{v:.4f}"
    return str(v)


def build_results_md(repo_root: str | Path = ".", out: str | Path = "RESULTS.md") -> Path:
    """Aggregate every ``experiments/*/RESULTS.csv`` into a sorted root ``RESULTS.md``.

    Coalesces the heterogeneous per-experiment CSVs into
    ``[experiment, arm, bucket_mean, acc_ID, acc_OOD, verdict, note]``, sorts DESC
    by ``bucket_mean`` (blank/NaN sink to the bottom), and writes a Markdown table.
    Returns the path written.
    """
    root = Path(repo_root)
    csvs = sorted(root.glob("experiments/*/RESULTS.csv"))
    rows: list[dict] = []
    for csv in csvs:
        try:
            rows.extend(_coalesce_rows(csv))
        except Exception as exc:  # noqa: BLE001
            logger.warning("skipping %s: %s", csv, exc)

    df = pd.DataFrame(rows, columns=_VIEW)
    if not df.empty:
        df = df.sort_values("bucket_mean", ascending=False, na_position="last").reset_index(drop=True)

    lines = [
        "# Results ledger",
        "",
        "Auto-generated by `frame.ledger.build_results_md` from every "
        "`experiments/*/RESULTS.csv`. Do NOT hand-edit — regenerate.",
        "",
        "`bucket_mean` (unweighted mean over the 4 real capability_group × {ID,OOD} "
        "buckets, canonical headline from `frame.metrics.stratified_report`) is the "
        "number we track; rows are sorted by it. A blank `bucket_mean` means that "
        "experiment's `RESULTS.csv` predates the canonical column (see `note`).",
        "",
        "| " + " | ".join(_VIEW) + " |",
        "| " + " | ".join("---" for _ in _VIEW) + " |",
    ]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join(_fmt(r[c]) for c in _VIEW) + " |")
    lines.append("")

    out_path = root / out if not Path(out).is_absolute() else Path(out)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote %s (%d rows from %d experiments)", out_path, len(df), len(csvs))
    return out_path
